# ----------------------------------------------------
# Type:
# classic: Only break logs above the log you broke
# classic-leaves: Like classic, excepts breaks all leaves.
# full: Breaks all logs and leaves connected.
# full-noleaves: Breaks all logs connected.
# ----------------------------------------------------
# Lumberjack-items:
# These are the items you can hold when you destroy logs.
# Currently, the items below are the only ones supported.
# These are the defaults:
# wooden - Wooden Axe
# stone - Stone Axe
# iron - Iron Axe
# golden - Golden Axe
# diamond - Diamond Axe
# ----------------------------------------------------

type: classic
tools:
 - wooden
 - stone
 - iron
 - golden
 - diamond
 
 
 