# ----------------------------------------------------
# Type:
# classic: Only break logs above the log you broke
# classic-leaves: Like classic, excepts breaks all leaves.
# full: Breaks all logs and leaves connected.
# full-noleaves: Breaks all logs connected.
# ----------------------------------------------------
# Lumberjack-tools:
# These are the items you can hold when you destroy logs.
# All materials are usable.
# ----------------------------------------------------

config-version: 2
type: classic
tools:
 - WOODEN_AXE
 - STONE_AXE
 - IRON_AXE
 - GOLDEN_AXE
 - DIAMOND_AXE
 
 
 