name: Lumberjack
version: "0.3.0-DEVELOPMENT"
authors: [Ryaan, DevSnox]
main: com.gageryanplugins.lumberjack.Lumberjack
api-version: 1.13
description: Makes cutting down trees much easier!
permission:
    lumberjack.use:
        description: Whoever has this permission is able to use the plugin.
        default: op