name: Lumberjack
version: 0.3.0
author: Ryaan
main: com.gageryanplugins.lumberjack.Main
api-version: 1.15
description: Makes cutting down trees much easier!
permission:
    lumberjack.use:
        description: Whoever has this permission is able to use the plugin.
        default: op